# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculatePotentialCIFs_parallel <- function(x_l, log_p0, alpha_tmp_1_vec, alpha_tmp_2_vec, beta_tmp_1, beta_tmp_2, effect1, effect2, prob_bound, method = "BFGS", maxit = 100L, reltol = 1e-8) {
    .Call(`_polyreg_calculatePotentialCIFs_parallel`, x_l, log_p0, alpha_tmp_1_vec, alpha_tmp_2_vec, beta_tmp_1, beta_tmp_2, effect1, effect2, prob_bound, method, maxit, reltol)
}

calculatePotentialCIFs_roptim <- function(log_p0, alpha_tmp_1, beta_tmp_1, alpha_tmp_2, beta_tmp_2, effect1, effect2, prob_bound, method = "BFGS", maxit = 100L, reltol = 1e-8) {
    .Call(`_polyreg_calculatePotentialCIFs_roptim`, log_p0, alpha_tmp_1, beta_tmp_1, alpha_tmp_2, beta_tmp_2, effect1, effect2, prob_bound, method, maxit, reltol)
}

test_stop_check <- function(log_p0) {
    invisible(.Call(`_polyreg_test_stop_check`, log_p0))
}

calculatePotentialCIFs_roptim_all <- function(x_l, log_p0, alpha_tmp_1_vec, alpha_tmp_2_vec, beta_tmp_1, beta_tmp_2, effect1, effect2, prob_bound, method = "BFGS", maxit = 100L, reltol = 1e-8) {
    .Call(`_polyreg_calculatePotentialCIFs_roptim_all`, x_l, log_p0, alpha_tmp_1_vec, alpha_tmp_2_vec, beta_tmp_1, beta_tmp_2, effect1, effect2, prob_bound, method, maxit, reltol)
}

calculateKM_rcpp <- function(t, d, w = as.numeric( c()), strata = as.integer( c()), error = "greenwood") {
    .Call(`_polyreg_calculateKM_rcpp`, t, d, w, strata, error)
}

