# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateKM_rcpp <- function(t, d, w = as.numeric( c()), strata = as.integer( c()), error = "greenwood") {
    .Call('_polyreg_calculateKM_rcpp', PACKAGE = 'polyreg', t, d, w, strata, error)
}

